### ISSUE TITLE
can't turn it off

### ISSUE THREAD

**Issue by galak6** [alexisisaac/MashedPixels#1]
hi,

first, you have made a great job doing that. I was starting to have a headacke trying to make my christmas light with my arduino uno and a ws2811 led strip when I found your github about that. Thanks a lot !

I upload the code in my arduino uno, apparently it's the reset button we have to use to change mode but when I hold it to turn it off with all the led going white to fade out, it doesn't work. It just keep changing mode. Perhaps i'm missing something but I don't really understand the code concerning the reset button.

I hook my led strip via the pin 6 and put it 100 for the number of led. 

thanks !

**Comment by alexisisaac** [comment]
Sorry I just saw your comment...

When using the reset button for changing modes you cannot turn it off. The ony option is to remove the power...
