### ISSUE TITLE
Complie Issue : Multiple Function Definitions

### ISSUE THREAD

**Issue by ghost** [alexisisaac/MashedPixels#2]
Am compiling this environment with the Arduino IDE compiler version 1.0.5 and am getting multiple definition errors for each Mode function from the .cpp file.  Am not a C or C++ programmer and am having trouble fixing this based on Internet research.  Here is an example of the errors from AntsMode.cpp:

MashedPixels\AntsMode.cpp.o: In function `AntsMode':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:8: multiple definition of`AntsMode::AntsMode(unsigned char, int)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build4396087434405219330.tmp/AntsMode.cpp:8: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:8: multiple definition of`AntsMode::AntsMode(unsigned char, int)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build4396087434405219330.tmp/AntsMode.cpp:8: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode::loop(CRGB*)':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:19: multiple definition of`AntsMode::loop(CRGB*)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build4396087434405219330.tmp/AntsMode.cpp:19: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode::init()':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:12: multiple definition of`AntsMode::init()'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build4396087434405219330.tmp/AntsMode.cpp:12: first defined here

**Comment by alexisisaac** [comment]
Hi can you try with only this code in your main file : 

```
#include "FastSPI_LED2.h"

#define USE_MATHIEUMODE
#define USE_EIFFELMODE
#define USE_ANTSMODE
#define USE_CALIBRATEMODE
#define USE_TRADITIONALMODE
#define USE_REDWAVEMODE
#define USE_VIDEOMODE
#define USE_ICECRYSTALSMODE


#ifdef USE_MATHIEUMODE
#include "MathieuMode.h"
#endif
#ifdef USE_EIFFELMODE
#include "EiffelMode.h"
#endif
#ifdef USE_ANTSMODE
#include "AntsMode.h"
#endif
#ifdef USE_CALIBRATEMODE
#include "CalibrateMode.h"
#endif
#ifdef USE_TRADITIONALMODE
#include "TraditionalMode.h"
#endif
#ifdef USE_REDWAVEMODE
#include "RedWaveMode.h"
#endif
#ifdef USE_ICECRYSTALSMODE
#include "IceCrystalsMode.h"
#endif



#ifdef USE_VIDEOMODE
#define FRAME_TIME 67 //milliseconds per frame
#define BITS_PER_PIXELS 24 //Bits per pixels
#define BITS_PER_PIXELS_24 //Bits per pixels
#define FRAMES_COUNT 301 //frames
#define SD_DATA
#endif
void loop(){
}
void setup(){

}
```

And can you try commenting and de commenting those line to see which one(s) create the problem : 

```
#define USE_MATHIEUMODE
#define USE_EIFFELMODE
#define USE_ANTSMODE
#define USE_CALIBRATEMODE
#define USE_TRADITIONALMODE
#define USE_REDWAVEMODE
#define USE_VIDEOMODE
#define USE_ICECRYSTALSMODE
```

**Comment by ghost** [comment]
Hello Alexis,

Thank you for the prompt response.

Main file sketch above complied in the Ardunio IDE without errors.  

Bob

**Comment by ghost** [comment]
Closed in error.  Sorry.

While the main sketch provided above compiles without error,  it is only a small portion of the MashedPixels sketch.  MashedPixels sketch will still produce multiple definition errors when compiled using the Arduino IDE.

**Comment by alexisisaac** [comment]
You are right I'm just trying to figure out where the problem occurs as the arduino compiler sometimes doesn't give the correct line number for an error.

Can you try the following : 

# 1

Adding those lines at the beginning after `#include "FastSPI_LED2.h"` : 

```
#include <Wire.h>
#include <EEPROM.h>
```

# 2

Then trying this code : 

```
#include "FastSPI_LED2.h"
#include <Wire.h>
#include <EEPROM.h>

#define USE_MATHIEUMODE
#define USE_EIFFELMODE
#define USE_ANTSMODE
#define USE_CALIBRATEMODE
#define USE_TRADITIONALMODE
#define USE_REDWAVEMODE
#define USE_VIDEOMODE
#define USE_ICECRYSTALSMODE


//Customize here
#define DATA_PIN 2  
#define BUTTON_PIN 3
#define NUM_LEDS 100

#define USE_RESET_AS_BUTTON
#define SERIAL_DEBUG


#ifdef SERIAL_DEBUG
#define MODE_EXPORT_MNAME
#endif

#ifdef USE_MATHIEUMODE
#include "MathieuMode.h"
#endif
#ifdef USE_EIFFELMODE
#include "EiffelMode.h"
#endif
#ifdef USE_ANTSMODE
#include "AntsMode.h"
#endif
#ifdef USE_CALIBRATEMODE
#include "CalibrateMode.h"
#endif
#ifdef USE_TRADITIONALMODE
#include "TraditionalMode.h"
#endif
#ifdef USE_REDWAVEMODE
#include "RedWaveMode.h"
#endif
#ifdef USE_ICECRYSTALSMODE
#include "IceCrystalsMode.h"
#endif



#ifdef USE_VIDEOMODE
#define FRAME_TIME 67 //milliseconds per frame
#define BITS_PER_PIXELS 24 //Bits per pixels
#define BITS_PER_PIXELS_24 //Bits per pixels
#define FRAMES_COUNT 301 //frames
#define SD_DATA
#endif

#define DATA_SIZE 300
byte *data;
//char files[13][13];

//Menu modes
enum mode_display {
#ifdef USE_MATHIEUMODE
  MODE_DISPLAY_MATHIEU,
#endif
#ifdef USE_EIFFELMODE
  MODE_DISPLAY_EIFFEL,
#endif
#ifdef USE_ANTSMODE
  MODE_DISPLAY_ANTS,
#endif
#ifdef USE_CALIBRATEMODE
  MODE_DISPLAY_CALIBRATE,
#endif
#ifdef USE_TRADITIONALMODE
  MODE_DISPLAY_TRADITIONAL,
#endif
#ifdef USE_REDWAVEMODE
  MODE_DISPLAY_REDWAVE,
#endif
#ifdef USE_VIDEOMODE
  MODE_DISPLAY_VIDEO,
#endif
#ifdef USE_ICECRYSTALSMODE
  MODE_DISPLAY_ICECRYSTALS,
#endif
};

#ifdef USE_VIDEOMODE
#ifdef SD_DATA
#include <SdFat.h>
#include <SdFatUtil.h>

// SD chip select pin
const uint8_t chipSelect = 4;
SdFat sd;
SdFile file;
char videofile[13];

//#define error(s) sd.errorHalt_P(PSTR(s))
#define error(s) void(s)
#endif
#endif
CRGB leds[NUM_LEDS+1];
unsigned long lastFrame = 0;
unsigned long startTime = 0;
boolean fr_count;
byte MAX_MODE = 0;
#ifdef USE_MATHIEUMODE
MathieuMode mat = MathieuMode( NUM_LEDS);
#endif
#ifdef USE_EIFFELMODE
EiffelMode ef = EiffelMode(false, NUM_LEDS);
#endif
#ifdef USE_ANTSMODE
AntsMode ant = AntsMode(true, NUM_LEDS);
#endif
#ifdef USE_CALIBRATEMODE
CalibrateMode cal = CalibrateMode(NUM_LEDS);
#endif
#ifdef USE_TRADITIONALMODE
TraditionalMode trad = TraditionalMode( NUM_LEDS);
#endif
#ifdef USE_REDWAVEMODE
RedWaveMode rw = RedWaveMode(NUM_LEDS);
#endif
#ifdef USE_ICECRYSTALSMODE
IceCrystalsMode ice = IceCrystalsMode(NUM_LEDS);
#endif

enum mode_display mode;
boolean file_initialized = false;

void loop(){
}
void setup(){

}
```

**Comment by ghost** [comment]
Cut and pasted the above sketch into the Arduino IDE.  After commenting out the SDChip Select pin commands; the sketch above compiled without error.  Saved the sketch to the MashedPixels folder in the Ardunio Libraries as MashedPixels.ino.  Closed the IDE.  Opened the saved .ino file up with the IDE and complied it again, this time I got the function multiple definitions.  Screen shot attached. 
![mashedpixelscapture](https://cloud.githubusercontent.com/assets/7865186/3322429/a6293010-f74a-11e3-8553-32480759828d.PNG)

  Something wrong in the way I'm saving the file and recompiling it?

MashedPixels\AntsMode.cpp.o: In function `AntsMode':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:8: multiple definition of`AntsMode::AntsMode(unsigned char, int)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build1876165025710421241.tmp/AntsMode.cpp:8: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:8: multiple definition of`AntsMode::AntsMode(unsigned char, int)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build1876165025710421241.tmp/AntsMode.cpp:8: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode::loop(CRGB*)':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:19: multiple definition of`AntsMode::loop(CRGB*)'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build1876165025710421241.tmp/AntsMode.cpp:19: first defined here

MashedPixels\AntsMode.cpp.o: In function `AntsMode::init()':
C:\Users\bobmu_000\Documents\Arduino\libraries\MashedPixels/AntsMode.cpp:12: multiple definition of`AntsMode::init()'
AntsMode.cpp.o:C:\Users\BOBMU_~1\AppData\Local\Temp\build1876165025710421241.tmp/AntsMode.cpp:12: first defined here

**Comment by alexisisaac** [comment]
It is really really strange : I have setup a new environment downloading the latest version of the arduino IDE 1.0.5 the latest version of the FastLed library (https://github.com/FastLED/FastLED/releases) and downloading the latest sources of mashed pixels ...

The only way I had to reproduce this behavior is to duplicate the MashedPixels folder into the library folder...

Can you check the MashedPixels folder isn't present in your library ?

**Comment by ghost** [comment]
That was the problem Alexis.  I removed the MashedPixels folder from \ardunio\libraries and placed it under \ardunio and now am able to complie, change the main sketch, recompile it, save it and recompile it again error-free.  Thank you for the assistance!

Now, how is the button wired into the circuit for a 3-wire strip of WS2812B LED's?  The three wires I have connected to the LED strip are + and - from a separate power supply with the - also connected to the - on the Arduino board, and data from Pin 3.   I looked at the demo videos and it looks like Pin 2 gets connected to the - through the button.  Is that correct my friend?

**Comment by ghost** [comment]
Program is working without button to change modes.  You do beautiful work!

**Comment by alexisisaac** [comment]
Thanks :-)

**Comment by alexisisaac** [comment]
> Now, how is the button wired into the circuit for a 3-wire strip of WS2812B LED's? The three wires I have connected to the LED strip are + and - from a separate power supply with the - also connected to the - on the Arduino board, and data from Pin 3. I looked at the demo videos and it looks like Pin 2 gets connected to the - through the button. Is that correct my friend?

It should be connected to the - directly but It's possible that I wire the Strip- to the button Pin2 and the Button Pin4 to the common ground because the button I use have 4 pins with 2 connected pairs Pin1 connected to Pin3 and Pin2 connected to Pin4.

**Comment by Rosspunk** [comment]
Alexis, Can you explain why this will not compile?
![image](https://cloud.githubusercontent.com/assets/10786683/6313698/3dc00f3c-b9b2-11e4-9261-f27e3e7e1b72.png)

**Comment by ghost** [comment]
I have seen this before.  You probably have the program I the wrong folder.  Make sure it is directly under the Arduino folder, not the Arduino/Libraries folder.  
  
Bob 

----- Original Message -----

**Comment by Rosspunk** [comment]
Alexsis, got it sorted. Had to manually add to the library in the ide. Looks a treat. Thanks.

Sent from Samsung Mobile

-------- Original message --------
