### ISSUE TITLE
Color Control

### ISSUE THREAD

**Issue by ghost** [alexisisaac/MashedPixels#3]
Modes are beautiful.  I know the color control is assigned by the LEDS operator.  Can't figure out how it is being assigned.  Could you show me for example how you are setting the green color for AntsMode or the red color for RedWaveMode?

**Comment by alexisisaac** [comment]
I'll try to explain the AntsMode code : 

```
#include "AntsMode.h"
```

Here I Include the name of the mode to be displayed in serial debug (if enabled) It can also be useful if in a later version a display is added.

```
#ifdef MODE_EXPORT_NAME
const char *AntsMode::name = "Ants";
#endif
```

The constructor : here the first parameter is a boolean to tell if the particles are "bouncing" off the edges of the strip or if they loop. The second one is the number of particles.
Those values are stored and used later.

```
AntsMode::AntsMode(boolean pBounces, int pCount){
  count = pCount;
  bounces = pBounces;
}
```

The init method is called when the mode is about to be used. here it initializes all the particles.
A particle is a `struct` with 3 parameters direction (left or right) a speed and position (between 0 and 1).

```
void AntsMode::init(){
  for (int a=0;a<ANTS_COUNT;a++){
    ants[a].position = random(10,1000)/1000.0f;
    ants[a].speed = random(10,500)/100000.0f;
    ants[a].direction = random(0,1000)>500;
  }
}
```

The loop method is called whenever the strip can be updated. The parameter is a pointer to the array of CRGB used by FastLed to update the strip.

```
void AntsMode::loop(CRGB *leds){
```

The following declaration and setRGB call is useless and will be removed It's probaby a remain of an old version.

```
   CRGB color;
   color.setRGB(random(0,255),random(0,255),random(0,255));
```

Here I loop between the first and the `count-1` particle and dim them (I divide each chanel by 1.02 (In fact I multiply by 9.8/10 wich is equivalent) then I remove 1 to reach 0 faster then constrain the result between 0 and 255).

```
   for(int whiteLed = 0; whiteLed < count; whiteLed = whiteLed + 1) {
      leds[whiteLed].g = constrain(9.8*leds[whiteLed].g/10.0-1, 0, 255);
      leds[whiteLed].r = constrain(9.8*leds[whiteLed].r/10.0-1, 0, 255);
      leds[whiteLed].b = constrain(9.8*leds[whiteLed].b/10.0-1, 0, 255);
   }
```

Then I loop again between all particles and updates their position  based on their speed and their direction.

```
  for (int a=0;a<ANTS_COUNT;a++){
    ants[a].position += ants[a].speed*(ants[a].direction?1:-1);
```

If a particle reaches the end or the beginning of the strip the code reverts the direction if `bounces`has been set in the constructor or make it appear at the opposite end of the strip.

```
    if(ants[a].position>1 || ants[a].position<0){
      if(bounces){
        ants[a].direction = !ants[a].direction;
      } else if(ants[a].position>1){
        ants[a].position = ants[a].position-1;
      } else {
        ants[a].position = 1+ants[a].position;
      }
    }
```

Then I finally use the data stored in the particles to update the led strip. I increase the values of the channels of the pixel at coordinate `position*count` So `position=0` is `led[0]` and `position=1`is `led[count]`. I use this method so if 2 particles are at the same position the pixel will be brighter.

```
    CRGB *led = &leds[round(ants[a].position*count)];
    led->r = constrain(led->r+10, 0,255);
    led->b = constrain(led->b+2, 0,255);
    led->g = constrain(led->g+5, 0,255);
  }
}
```

**Comment by ghost** [comment]
If the setRGB "CRGB color" line is useless, then how are you setting the color of the LED to Green?  What line of code would I change to set the ants color to red, or brown, or gold, or white?

**Comment by alexisisaac** [comment]
```
    led->r = constrain(led->r+10, 0,255);
    led->b = constrain(led->b+2, 0,255);
    led->g = constrain(led->g+5, 0,255);
```

Those lines set the colors. In the FastLED library I'm using with my strip it seems that there is a mix up of the red and green channel. Thats why I'm setting the green color to `led->r``

To set another color you can : 
Either define a solid color regardless of if the pixel is already lit (by another particle or by the trail of a particle) this way (this should be orange): 

```
    led->r = 140;
    led->b = 0;
    led->g = 255;
```

Or either "add" the color to the current color of the pixel (this should be gold): 

```
    led->r = constrain(led->r+24, 0,255);
    led->b = constrain(led->b+15, 0,255);
    led->g = constrain(led->g+25, 0,255);
```

You can determine the values to use using a tool like this one http://www.colorpicker.com/ pick a color and use the values for red(R), green(G), and blue(B) if you want to add color to the current pixel you should probably divide all channels by the same amount to avoid having particles too bright.

**Comment by ghost** [comment]
Thank you for the explanation Alexis.  I will close this issue.  I will look forward to experimenting with different versions of your base code.  You mentioned that you have a mixup of the red and green channel.  Here is a short sketch available from the FastLED examples library that I have found helpful:

#include "FastLED.h"

////////////////////////////////////////////////////////////////////////////////////////////////////
//
// RGB Calibration code
//
// Use this sketch to determine what the RGB ordering for your chipset should be.  Steps for setting up to use:

// \* Uncomment the line in setup that corresponds to the LED chipset that you are using.  (Note that they
//   all explicitly specify the RGB order as RGB)
// \* Define DATA_PIN to the pin that data is connected to.
// \* (Optional) if using software SPI for chipsets that are SPI based, define CLOCK_PIN to the clock pin
// \* Compile/upload/run the sketch 

// You should see six leds on.  If the RGB ordering is correct, you should see 1 red led, 2 green 
// leds, and 3 blue leds.  If you see different colors, the count of each color tells you what the 
// position for that color in the rgb orering should be.  So, for example, if you see 1 Blue, and 2
// Red, and 3 Green leds then the rgb ordering should be BRG (Blue, Red, Green).  

// You can then test this ordering by setting the RGB ordering in the addLeds line below to the new ordering
// and it should come out correctly, 1 red, 2 green, and 3 blue.
//
//////////////////////////////////////////////////

#define NUM_LEDS 6

// Data pin that led data will be written out over
#define DATA_PIN 6
// Clock pin only needed for SPI based chipsets when not using hardware SPI
//#define CLOCK_PIN 8

CRGB leds[NUM_LEDS];

void setup() {
    // sanity check delay - allows reprogramming if accidently blowing power w/leds
    delay(2000);

```
  // Uncomment one of the following lines for your leds arrangement.
  // FastLED.addLeds<TM1803, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<TM1804, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<TM1809, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<WS2811, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<WS2812, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);
  // FastLED.setBrightness(CRGB(255,255,255));
  // FastLED.addLeds<GW6205, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<GW6205_400, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<UCS1903, DATA_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<UCS1903B, DATA_PIN, RGB>(leds, NUM_LEDS);

  // FastLED.addLeds<WS2801, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<SM16716, RGB>(leds, NUM_LEDS);
  FastLED.addLeds<LPD8806, 9, 10, RGB>(leds, NUM_LEDS);

  // FastLED.addLeds<WS2801, DATA_PIN, CLOCK_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<SM16716, DATA_PIN, CLOCK_PIN, RGB>(leds, NUM_LEDS);
  // FastLED.addLeds<LPD8806, DATA_PIN, CLOCK_PIN, RGB>(leds, NUM_LEDS);
```

}

void loop() {
   leds[0] = CRGB(255,0,0); 
   leds[1] = CRGB(0,255,0);
   leds[2] = CRGB(0,255,0);
   leds[3] = CRGB(0,0,255);
   leds[4] = CRGB(0,0,255);
   leds[5] = CRGB(0,0,255);
   leds[random8()%NUM_LEDS] = CRGB(0,0,0);
   // leds[10] = CRGB(0,0,0);
   FastLED.show();
   // delay(1000);
   FastLED.showColor(CRGB::Black);
